# Testing the new shorter horizontal line
print("📋 Ваши дедлайны (2):")
print()
print("1. стрей кидс")
print("⏰ 07.12.2025 00:00")
print()
print("2. de =d vovu") 
print("⏰ 10.12.2025 00:00")
print("📝 Песня тест")
print()
print("─" * 20)  # This is the new shorter line
print("👤 Ник: vj_games")
print("📅 Ближайший дедлайн: 07.12.2025 00:00")
print("🎵 Песня: -")
print()
print("⚠️ Если что-то не успеваете — пишите админам")